(defun inspiration-753559 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/753559/"
  (interactive)
  (color-theme-install
   '(inspiration-753559
     ((background-color . "#000006")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#A68374"))))
     (font-lock-constant-face ((t (:foreground "#8A968F"))))
     (font-lock-builtin-face ((t (:foreground "#00F562"))))
     (font-lock-function-name-face ((t (:foreground "#00F70E"))))
     (font-lock-variable-name-face ((t (:foreground "#35E900"))))
     (font-lock-keyword-face ((t (:foreground "#61FF00"))))
     (font-lock-string-face ((t (:foreground "#6BCC00"))))
     (font-lock-doc-string-face ((t (:foreground "#6BCC00"))))
     (font-lock-type-face ((t (:foreground "#21FF00"))))
     )))

(provide 'inspiration-753559)
